-- =====================================================================
-- Group 5: Administration & Identity Management
-- PostgreSQL schema (mirrors the tables Django creates with `migrate`)
-- Usage:  psql -U postgres -d identity_db -f docs/schema.sql
-- =====================================================================

-- CREATE DATABASE identity_db;   -- run once, then connect to it

BEGIN;

-- ---------------------------------------------------------------------
-- Django core: content types
-- ---------------------------------------------------------------------
CREATE TABLE django_content_type (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label  VARCHAR(100) NOT NULL,
    model      VARCHAR(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_uniq UNIQUE (app_label, model)
);

-- ---------------------------------------------------------------------
-- Authentication: users, groups, permissions
-- ---------------------------------------------------------------------
CREATE TABLE auth_user (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password     VARCHAR(128)  NOT NULL,
    last_login   TIMESTAMPTZ,
    is_superuser BOOLEAN       NOT NULL DEFAULT FALSE,
    username     VARCHAR(150)  NOT NULL UNIQUE,
    first_name   VARCHAR(150)  NOT NULL DEFAULT '',
    last_name    VARCHAR(150)  NOT NULL DEFAULT '',
    email        VARCHAR(254)  NOT NULL DEFAULT '',
    is_staff     BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN       NOT NULL DEFAULT TRUE,
    date_joined  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE auth_group (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE auth_permission (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    content_type_id INTEGER      NOT NULL REFERENCES django_content_type (id) ON DELETE CASCADE,
    codename        VARCHAR(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_codename_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE auth_group_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id      INTEGER NOT NULL REFERENCES auth_group (id)      ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES auth_permission (id) ON DELETE CASCADE,
    CONSTRAINT auth_group_permissions_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE auth_user_groups (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL REFERENCES auth_user (id)  ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES auth_group (id) ON DELETE CASCADE,
    CONSTRAINT auth_user_groups_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE auth_user_user_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES auth_user (id)       ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES auth_permission (id) ON DELETE CASCADE,
    CONSTRAINT auth_user_user_permissions_uniq UNIQUE (user_id, permission_id)
);

-- ---------------------------------------------------------------------
-- App tables: accounts.Profile and accounts.ActivityLog
-- ---------------------------------------------------------------------
CREATE TABLE accounts_profile (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL UNIQUE REFERENCES auth_user (id) ON DELETE CASCADE,
    phone       VARCHAR(30)  NOT NULL DEFAULT '',
    department  VARCHAR(100) NOT NULL DEFAULT '',
    bio         TEXT         NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE accounts_activitylog (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      REFERENCES auth_user (id) ON DELETE SET NULL,
    username    VARCHAR(150) NOT NULL DEFAULT '',
    action      VARCHAR(30)  NOT NULL
                CHECK (action IN ('login','logout','login_failed','register',
                                  'profile_update','user_activated','user_deactivated')),
    ip_address  INET,
    user_agent  VARCHAR(255) NOT NULL DEFAULT '',
    details     VARCHAR(255) NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX accounts_activitylog_created_at_idx ON accounts_activitylog (created_at);
CREATE INDEX accounts_activitylog_user_id_idx    ON accounts_activitylog (user_id);
-- speeds up the "5 failed logins in 15 minutes" lockout check
CREATE INDEX accounts_activitylog_lockout_idx    ON accounts_activitylog (username, action, created_at);

-- ---------------------------------------------------------------------
-- Sessions and admin history
-- ---------------------------------------------------------------------
CREATE TABLE django_session (
    session_key  VARCHAR(40) PRIMARY KEY,
    session_data TEXT        NOT NULL,
    expire_date  TIMESTAMPTZ NOT NULL
);
CREATE INDEX django_session_expire_date_idx ON django_session (expire_date);

CREATE TABLE django_admin_log (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time     TIMESTAMPTZ  NOT NULL,
    object_id       TEXT,
    object_repr     VARCHAR(200) NOT NULL,
    action_flag     SMALLINT     NOT NULL CHECK (action_flag >= 0),
    change_message  TEXT         NOT NULL,
    content_type_id INTEGER      REFERENCES django_content_type (id) ON DELETE SET NULL,
    user_id         INTEGER      NOT NULL REFERENCES auth_user (id)  ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- Default groups used by the project (same as `manage.py setup_groups`,
-- permissions are attached by that command after `migrate`)
-- ---------------------------------------------------------------------
INSERT INTO auth_group (name) VALUES ('Administrator'), ('Staff Manager'), ('Member');

COMMIT;

-- ---------------------------------------------------------------------
-- Handy queries
-- ---------------------------------------------------------------------
-- Users with their groups:
--   SELECT u.username, u.email, u.is_active, string_agg(g.name, ', ') AS groups
--   FROM auth_user u
--   LEFT JOIN auth_user_groups ug ON ug.user_id = u.id
--   LEFT JOIN auth_group g        ON g.id = ug.group_id
--   GROUP BY u.id ORDER BY u.username;
--
-- Failed logins in the last 15 minutes:
--   SELECT username, COUNT(*) FROM accounts_activitylog
--   WHERE action = 'login_failed' AND created_at > NOW() - INTERVAL '15 minutes'
--   GROUP BY username HAVING COUNT(*) >= 5;
